spring:
  main:
    allow-bean-definition-overriding: true
  output:
    ansi:
      enabled: ALWAYS   #控制台彩色打印输出
  mvc:
    throw-exception-if-no-handler-found: true
  data:
    mongodb:
      uri: mongodb://bergwong:Er8^KZe*@192.168.26.81:27017,192.168.26.82:27017,192.168.26.83:27017/cgp2_dev
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 100MB
  #spring redis连接配置
  ###############################
  redis:
    time-out: 5000ms
    #spring jedis连接池
    sentinel:
      master: mymaster
      nodes: 192.168.26.84:26379,192.168.26.85:26379,192.168.26.86:26379
      password: Dev!123a
    #默認連接db
    database: 0
    password: Dev!123a
    client-type: lettuce
  security:
    oauth2:
      resourceserver:
        opaquetoken:
          client-id: innerapi
          client-secret: rzTWWxo4Sb2Xq9
          introspection-uri: http://192.168.26.70/cgp2-oauth/oauth/check_token
  cloud:
    discovery:
      enabled: true
      client:
        health-indicator:
          enabled: true
        simple:
          instances:
            cgp-service:
              - uri: http://127.0.0.1
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include:
          - beans
          - health
          - httptrace
          - threaddump
server:
  servlet:
    context-path: /cgp-social-rest
  port: 8081